name: test_php

on: [push]

jobs:
  test:
    name: test with phpunit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run phptunit on Docker container
      run: |
        php -v
        pwd
        ls
        docker-compose up -d
        composer install
        docker-compose exec -T laravel.test bash -c "vendor/bin/phpunit"
